name: Node CI

on: [push]

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js latest
        uses: actions/setup-node@v6
        with:
          node-version: "*"
      - name: Install dependencies
        run: |
          yarn install
          yarn check
      - name: Build artifact
        run: |
          yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: bundled
          path: dist

  test:
    needs: check-and-build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get test dependencies versions
        id: test-dep-versions
        shell: bash  # <--- Crucial for Windows compatibility with $GITHUB_OUTPUT as Powershell uses a different syntax
        run: |
          echo "postcss-tape=$(node scripts/get-dev-deps postcss-tape)" >> $GITHUB_OUTPUT
          echo "postcss=$(node scripts/get-dev-deps postcss)" >> $GITHUB_OUTPUT
      - name: yarn install
        run: |
          yarn workspaces focus -A --production
          yarn add --dev postcss-tape@${{ steps.test-dep-versions.outputs.postcss-tape }} postcss@${{ steps.test-dep-versions.outputs.postcss }}
      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          name: bundled
          path: dist
      - name: Test
        run: |
          yarn test:tape
